/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package easyscheduleworking;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;


/**
 *
 * @author Ty
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        departmentComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        departmentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select a department", "ACCOUNTING", "AEROSPACE STUDIES", "AFRICAN & AFRICAN-AMERICAN STU", "AGRIC & EXTENSION ED & EVALUAT", "AGRICULTURAL ECONOMICS", "AGRICULTURE", "AGRONOMY",
            "ANIMAL SCIENCES", "ANTHROPOLOGY", "ARABIC", "ARCHITECTURE", "ART", "ART HISTORY", "ASTRONOMY", "ATHLETIC TRAINING", "BASIC SCIENCES", "BIOLOGICAL ENGINEERING", "BIOLOGICAL SCIENCES",
            "BUSINESS ADMINISTRATION", "BUSINESS LAW", "CHEMICAL ENGINEERING", "CHEMISTRY", "CHILD AND FAMILY STUDIES", "CHINESE", "CIVIL ENGINEERING", "CLASSICAL STUDIES", "COMMUNICATION DISORDERS",
            "COMMUNICATION STUDIES", "COMPARATIVE BIOMEDICAL SCIENCE", "COMPARATIVE LITERATURE", "COMPUTER SCIENCE", "CONSTRUCTION MANAGEMENT", "CURRICULUM & INSTRUCTION", "DIGITAL MEDIA ARTS & ENGINEERI",
            "DOCTOR OF DESIGN", "ECONOMICS", "EDUC LEADERSHIP RESEARCH COUNS", "ELECTRICAL ENGINEERING", "ENGINEERING", "ENGLISH", "ENTOMOLOGY", "ENTREPRENEURSHIP", "ENVIRONMENTAL ENGINEERING",
            "ENVIRONMENTAL MANAGEMENT SYSTE", "ENVIRONMENTAL SCIENCES", "EXPERIMENTAL STATISTICS", "FINANCE", "FRENCH", "GENERAL BUSINESS", "GEOGRAPHY", "GEOLOGY", "GERMAN", "GREEK",
            "HEBREW", "HISTORY", "HONORS", "HORTICULTURE", "INDUSTRIAL ENGINEERING", "INFO SYSTEMS AND DECISION SCIE", "INTERIOR DESIGN", "INTERNATIONAL STUDIES", "ITALIAN", "KINESIOLOGY",
            "LANDSCAPE ARCHITECTURE", "LATIN", "LEADERSHIP & HUMAN RESOURCES D", "LIBERAL ARTS", "LIBRARY & INFORMATION SCIENCE", "LIFE COURSE AND AGING", "LINGUISTICS", "MANAGEMENT",
            "MARKETING", "MASS COMMUNICATION", "MATHEMATICS", "MECHANICAL ENGINEERING", "MEDICAL PHYSICS", "MILITARY SCIENCE", "MUSIC", "MUSIC EDUCATION", "NUTRITION & FOOD SCIENCES",
            "OCEANOGRAPHY & COASTAL SCIENCE", "PATHOBIOLOGICAL SCIENCES", "PETROLEUM ENGINEERING", "PHILOSOPHY", "PHYSICAL SCIENCE", "PHYSICS", "PLANT HEALTH", "POLITICAL SCIENCE", "PSYCHOLOGY",
            "PUBLIC ADMINISTRATION", "RELIGIOUS STUDIES", "RENEWABLE NATURA L RESOURCES", "SCREEN ARTS", "SOCIAL WORK", "SOCIOLOGY", "SPANISH", "STUDENT SUPPORT SERVICES",
            "TEXTILES,APPAREL & MERCHANDISI", "THEATRE", "UNIVERSITY STUDIES", "VETERINARY CLINICAL SCIENCES", "VETERINARY MEDICINE", "WOMEN'S AND GENDER STUDIES"}));
departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        departmentComboBoxActionPerformed(evt);
    }
    });

    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Courses"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.String.class
        };
        boolean[] canEdit = new boolean [] {
            false
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }
    });
    jScrollPane2.setViewportView(jTable2);
    if (jTable2.getColumnModel().getColumnCount() > 0) {
        jTable2.getColumnModel().getColumn(0).setResizable(false);
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(639, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(300, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        DBHelper courseHelper = new DBHelper();
        String[] allURL = {
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/828f62c3b11e2bc286258252002c2544?OpenDocument", //ACCOUNTING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e17ea9fb2fb3d2ae86258252002c2568?OpenDocument", //AEROSPACE STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/4278fb99e677044186258252002c2539?OpenDocument", //AFRICAN & AFRICAN-AMERICAN STUD
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/6bceaa70b3272c8c86258252002c254b?OpenDocument", //AGRIC & EXTENSION ED & EVALUAT
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e9a27e3a5315bd6786258252002c254c?OpenDocument", //AGRICULTURAL ECONOMICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/039c4edf6e3a164e86258252002c254e?OpenDocument", //AGRICULTURE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/32d14753374107db86258252002c2553?OpenDocument", //AGRONOMY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/b0622e8cf37def1c86258252002c2556?OpenDocument", //ANIMAL SCIENCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/ed12c9d9198032fb86258252002c2559?OpenDocument", //ANTHROPOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/a7aee170d4283e9386258252002c255c?OpenDocument", //ARABIC
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e656e1036a9a9f8f86258252002c255d?OpenDocument", //ARCHITECTURE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9f2b5fb860f7e63586258252002c2562?OpenDocument", //ART
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/3a66deed6b88c30c86258252002c2565?OpenDocument", //ART HISTORY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/4a9890aec720121686258252002c256a?OpenDocument", //ASTRONOMY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/14be38883d28f91586258252002c256d?OpenDocument", //ATHLETIC TRAINING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/bc38479f0f834c8486258252002c2572?OpenDocument", //BASIC SCIENCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/1ece310547e5198c86258252002c2573?OpenDocument", //BIOLOGICAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/8ba05ccb39dbd0a786258252002c257b?OpenDocument", //BIOLOGICAL SCIENCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e43a7336906523b686258252002c256f?OpenDocument", //BUSINESS ADMINISTRATION
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/fe1f789b46f3409586258252002c2580?OpenDocument", //BUSINESS LAW
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/470cd8d31ecb7e0d86258252002c2599?OpenDocument", //CHEMICAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/df6140b622df1fba86258252002c25a4?OpenDocument", //CHEMISTRY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9b53fcd209dbb82a86258252002c2596?OpenDocument", //CHILD AND FAMILY STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/4f584f6e1bdc7d0686258252002c25ad?OpenDocument", //CHINESE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/f029141c6d89fa2f86258252002c258e?OpenDocument", //CIVIL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/3b548780c909ff7786258252002c25b0?OpenDocument", //CLASSICAL STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/1a151a1489344a5f86258252002c25bd?OpenDocument", //COMMUNICATION DISORDERS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/720f3f3172efc00686258252002c25ba?OpenDocument", //COMMUNICATION STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/53761e8096cf5fc986258252002c2581?OpenDocument", //COMPARATIVE BIOMEDICAL SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/1159422d2935807a86258252002c25be?OpenDocument", //COMPARATIVE LITERATURE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/62cdc1025f30735686258252002c25c6?OpenDocument", //COMPUTER SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/882f9df15fc2772b86258252002c25b5?OpenDocument", //CONSTRUCTION MANAGEMENT
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/a224f810b872769086258252002c25d3?OpenDocument", //CURRICULUM & INSTRUCTION
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/821d756a7db9ff9786258252002c25cb?OpenDocument", //DIGITAL MEDIA ARTS & ENGINEERI
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/198c2c32976196ab86258252002c25c8?OpenDocument", //DOCTOR OF DESIGN
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/707244fc61548e4e86258252002c25cc?OpenDocument", //ECONOMICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/7ee9816e02656d1586258252002c25d9?OpenDocument", //EDUC LEADERSHIP RESEARCH COUNS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/92e27ab256cb0af086258252002c25d6?OpenDocument", //ELECTRICAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/ed0f98bf3792f38086258252002c25e7?OpenDocument", //ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e9d1a9a883764f2886258252002c25e4?OpenDocument", //ENGLISH
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/b00e964f3fa4091e86258252002c25ea?OpenDocument", //ENTOMOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/572c998bba17a4c986258252002c25ed?OpenDocument", //ENTREPRENEURSHIP
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/2eef146029f4ff5c86258252002c25f2?OpenDocument", //ENVIRONMENTAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/f6087be264d4eb1e86258252002c25dc?OpenDocument", //ENVIRONMENTAL MANAGEMENT SYSTE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/61404a1ea987ddc986258252002c25f0?OpenDocument", //ENVIRONMENTAL STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/727154eaf47ca2c286258252002c25f8?OpenDocument", //EXPERIMENTAL STATISTICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9588dc56341925fc86258252002c25fd?OpenDocument", //FINANCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/5524c4d0bd46371986258252002c25fe?OpenDocument", //FRENCH
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/c82bffbcdbdb4eff86258252002c2602?OpenDocument", //GENERAL BUSINESS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/bdf10bd3f8fa618c86258252002c2605?OpenDocument", //GEOGRAPHY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/a25659514d39a00086258252002c2608?OpenDocument", //GEOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/001ae36691c62fed86258252002c260b?OpenDocument", //GERMAN
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/b31a31bb47f473dd86258252002c260c?OpenDocument", //GREEK
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/672fc86388cb4c7286258252002c260e?OpenDocument", //HEBREW
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/ef644a9b763a42d986258252002c2611?OpenDocument", //HISTORY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/c5dbe1942a8d808e86258252002c2614?OpenDocument", //HONORS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/39fb84a5ab53e0a986258252002c2616?OpenDocument", //HORTICULTURE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/476c664f44ec654d86258252002c261e?OpenDocument", //INDUSTRIAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/7781e3092f6b68bb86258252002c2622?OpenDocument", //INFO SYSTEMS AND DECISION SCIE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/cf844095942a74ee86258252002c261b?OpenDocument", //INTERIOR DESIGN
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/dda65eabba3543ca86258252002c261f?OpenDocument", //INTERNATIONAL STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/8fda90a81b143aa486258252002c2624?OpenDocument", //ITALIAN
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/bf599682c49c5af486258252002c262a?OpenDocument", //KINESIOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/138f9a6377c6e10786258252002c262d?OpenDocument", //LANDSCAPE ARCHITECTURE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/d58db4c8eaa2a40a86258252002c263a?OpenDocument", //LATIN
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/473d4550120561fd86258252002c263d?OpenDocument", //LEADERSHIP & HUMAN RESOURCES D
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/94c18d07ae9f9bcc86258252002c2640?OpenDocument", //LIBERAL ARTS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/5cd2e5851d4c777786258252002c2643?OpenDocument", //LIBRARY & INFORMATION SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/fc8296d50c0d471a86258252002c263b?OpenDocument", //LIFE COURSE & AGING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9398d6bceef5855486258252002c2642?OpenDocument", //LINGUISTICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/b132a7a03d441cad86258252002c2656?OpenDocument", //MANAGEMENT
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/8d0142f3bc0f5b1586258252002c265b?OpenDocument", //MARKETING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/ca295c95c2a5703d86258252002c264e?OpenDocument", //MASS COMMUNICATION
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/465493d09e5b703086258252002c2649?OpenDocument", //MATHEMATICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/7f86e7502736bcd686258252002c2651?OpenDocument", //MECHANICAL ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/03b2559fa45f6f7e86258252002c2654?OpenDocument", //MEDICAL PHYSICS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/edfb69afde2555e286258252002c2659?OpenDocument", //MILITARY SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9cab963fa671e6a986258252002c2662?OpenDocument", //MUSIC
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/83dec385628e74e786258252002c265c?OpenDocument", //MUSIC EDUCATION
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/91efd24c2156f85986258252002c2667?OpenDocument", //NUTRITION & FOOD SCIENCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/34784fc8adf0828286258252002c2669?OpenDocument", //OCEANOGRAPHY & COASTAL SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/f04b76f472ea7acd86258252002c266d?OpenDocument", //PATHOBIOLOGICAL SCIENCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/6df2f6b41033da3186258252002c2672?OpenDocument", //PETROLEUM ENGINEERING
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/4ec00a6ced2fc7f486258252002c2674?OpenDocument", //PHILOSOPHY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/8bc0b3625add04a586258252002c2677?OpenDocument", //PHYSICAL SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/7689eb29e8ec871586258252002c267f?OpenDocument", //PLANT HEALTH
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/268a3fa3efdee98586258252002c2680?OpenDocument", //POLITICAL SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/aa25082f8b14741986258252002c2685?OpenDocument", //PSYCHOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/5fcde11ead9b247086258252002c266c?OpenDocument", //PUBLIC ADMINISTRATION
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/bd85f1d43eb288fe86258252002c2686?OpenDocument", //RELIGIOUS STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/f799ddddd82ecafa86258252002c268b?OpenDocument", //RENEWABLE NATURAL RESOURCES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/5bf4a53bcddf2a1886258252002c268d?OpenDocument", //SCREEN ARTS
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/4ea34b9d54587e6586258252002c269b?OpenDocument", //SOCIAL WORK
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/87eeebc5ed45316086258252002c2691?OpenDocument", //SOCIOLOGY
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/2f43f14821c9aade86258252002c2694?OpenDocument", //SPANISH
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/1f45b337898492d986258252002c2696?OpenDocument", //STUDENT SUPPORT SERVICES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/88edc35614fedc3286258252002c269c?OpenDocument", //TEXTILES,APPAREL & MERCHANDISI
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/e53d786f17c6e86386258252002c269f?OpenDocument", //THEATRE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/a9aa3cf84a15d3b986258252002c26a1?OpenDocument", //UNIVERSITY STUDIES
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/d04e2ba23557e0f186258252002c26a2?OpenDocument", //VETRINARY CLINICAL SCIENCE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/aacddf740840abf486258252002c26a6?OpenDocument", //VETERINARY MEDICINE
            "http://appl101.lsu.edu/booklet2.nsf/bed33d8925ab561b8625651700585b85/9562574cfef6900686258252002c26a9?OpenDocument"}; //WOMAN'S AND GENDER STUDIES
        
        int i = departmentComboBox.getSelectedIndex();
        // implimentation of jTable
        courseHelper.loadURL(allURL[i-1]);
        String courseListTxt = courseHelper.getText();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        ArrayList<Course> courseList = courseHelper.parseText(courseListTxt);   //change course list to work
        Object rowData[] = new Object[1];
        for(int j = 0; j <courseList.size(); j++){      //either impliment parser or use working array for course list
            rowData[0] = courseList.get(j).name;         //either impliment parser or use working array
            model.addRow(rowData);
        }
        
        
        //String courseListTxt = courseHelper.getText();
        //DefaultTableModel tableModel = new DefaultTableModel(title, courseList.size());
        //for(int j = 0; j < courseList.size(); j++){
        //    tableModel
        //}
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
